name: cork
description: Yet another dependency injection framework for Dart.
homepage: https://github.com/matanlurey/cork
author: Matan Lurey <matanl@google.com>
version: 0.0.1-alpha.5
dependencies:
  analysis: ">=0.0.1-alpha.4 <0.1.0"
  collection: ">=1.1.1 <2.0.0"
  generator: ">=0.0.1-alpha.2 <0.1.0"
dev_dependencies:
  test: any
